### ISSUE TITLE
Server kicking players "internal server error"

### ISSUE THREAD

**Issue by BLSK** [eidehua/More-Health-Enhanced#2]
I have tried multiple things:
I noticed More Health 6.0 was a .zip so tried downloading 6.3 as a .zip and tried all combinations but I still keep getting booted.  I can't use 6.0 of course since when a player dies they can't respawn.
I just found I had a 6.2 version and a few others I forgot I had so I am looking at what may happen if I use them...
Here's the Error Report.  All the different ones look almost identical so...guessing might be?
http://pastebin.com/AVbv1McH

This is what 6.0 did:
![2015-06-09_12 40 23](https://cloud.githubusercontent.com/assets/8443396/8063820/dad60578-0ea4-11e5-848d-0b585eb05fa8.png)

I would click Respawn and it would just rekill me but not count it as a death
6.3 won't allow anyone to log in at all 
Plz help PLEASE!

**Comment by BLSK** [comment]
nvm... 6.0 seems to work right now... I do have a question though maybe you can answer....

Why is it your mod is always taking credit for other mods causing crashes?  It's very bazaar... very...

**Comment by eidehua** [comment]
There is a client side issue involving the keyboard class right now on my side (latest version server starts but players can't join it), but perhaps the respawning issue was an error in another mod. Maybe you thought it was my mod since my mod deals with health and respawning, and overlooked another mod doing some stuff with respawns as well. Or maybe it was a bug with our mod interactions.
